# Generated by Django 3.0.8 on 2020-08-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_administrador',
            field=models.BooleanField(default=True),
        ),
    ]
